### PR TITLE
Greatest espresso Tests ever

### PR DESCRIPTION
**Pull request by ldbonkowski**
### Describe your changes

This PR accomplishes the following:

- *Description of change 1...*
- *Description of change 2...*

### Issue ticket number and link

This PR addresses: #<link_to_issue>

### Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Necessary java docs are present
- [ ] Necessary UML diagrams are created
- [ ] Necessary tests are written

### Screenshots (if applicable)

e.g. UI screenshots, UML screenshots, etc

### CODE REVIEW

**Review by jdrco — APPROVED** [review]
Nice tests

**Review by Sami-Jagirdar — COMMENTED** [review]
Beautifuul, nothing wrong

**Review by Sami-Jagirdar — APPROVED** [review]
LGTM

**Review by owencooke — APPROVED** [review]
LOOKS AMAZING

**Pull request merged**
