### PR TITLE
Final UI changes

### PR DESCRIPTION
**Pull request by jdrco**
### Describe your changes

This PR accomplishes the following:
- dropdown order
- bottom padding in home page
- serial/scan icons
- placeholder in view item page
- gallery photos top padding Large
- delete modal
- date on view item

### CODE REVIEW

**Review by ldbonkowski — APPROVED** [review]
LGTM!

**Review by owencooke — APPROVED** [review]
thanks @jdrco for addressing those, it looks great!

**Review by MatthewNeufeld — APPROVED** [review]
Looks great - big shoutout to you @jdrco. LGTM!!!!!!!!!

**Review by Sami-Jagirdar — APPROVED** [review]
@jdrco I would buy this app because of how clean the UI looks. Great job everyone!

**Pull request merged**
