### PR TITLE
Base app theme/color code and Start of Add Item UI

### PR DESCRIPTION
**Pull request by owencooke**
Hoping to merge this PR a little early so that you all have reference into how to use the Material Design 3 components, and how I have overwritten some of the default colors in XML to match our files.

This PR includes:
- all colors used in Figma design (see `res/colors`)
- some overwritten TextInput and Menu XML styles for Material Design 3
- all the code for the Add Item page issue, other than form input validation. Features a calendar widget DatePicker for dates

Screenshot (649)

### CODE REVIEW

**Comment by owencooke** [comment]
@ldbonkowski successfully merged main onto this branch. Moved your list code from MainActivity into the HomeFragment class. 

I'm gonna try adding the Backend functionality for this basic add page

**Comment by owencooke** [comment]
We are ready for review! 🚀🚀

**Review by jdrco — COMMENTED** [review]
@owencooke I ran on my local and it all looks great! One thing I did notice though (and it may just be my device) is that the highlight of the nav doesn't move back to home after completing actions in the add fragment. Let me know if you think this is worth addressing in this PR.

This image is taken after pressing "check" or "back" in the add fragment which goes back to home, but the highlight doesn't update in the navbar.
Screenshot 2023-11-03 at 10 34 39 AM

**Comment by owencooke** [comment]
@jdrco Good catch, I didn't notice that. I suppose it depends on whether we want the active highlight or not.

In Figma, we do have the highlight around all the icons. I just can't figure out what property that is... that's why the purple is still there, it's the default, and I can't remove it.

**Comment by jdrco** [comment]
> @jdrco Good catch, I didn't notice that. I suppose it depends on whether we want the active highlight or not.
> 
> In Figma, we do have the highlight around all the icons. I just can't figure out what property that is... that's why the purple is still there, it's the default, and I can't remove it.

Sounds good. Can probably address this when I’m a PR that targets that issue

**Review by jdrco — APPROVED** [review]

**Review by ldbonkowski — APPROVED** [review]

**Pull request merged**
