### PR TITLE
Fix: empty make filter

### PR DESCRIPTION
**Pull request by jdrco**
### Describe your changes

This PR accomplishes the following:

- Empty make filter doesn't filter the item list

### Issue ticket number and link

This PR addresses: https://github.com/CMPUT301F23T08/HouseHomey/issues/59

### Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] Necessary java docs are present
- [x] Necessary UML diagrams are created
- [ ] Necessary tests are written

### Screenshots (if applicable)

### CODE REVIEW

**Review by antonio2uofa — APPROVED** [review]
What an elegant solution!

**Review by Sami-Jagirdar — APPROVED** [review]
Yep, copied the code and tried it on my branch. Works!

**Review by ldbonkowski — APPROVED** [review]
LGTM!

**Review by MatthewNeufeld — APPROVED** [review]
LGTM!!!

**Pull request merged**
